# Generated by Django 3.2 on 2023-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatternInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEST_ITEM', models.CharField(max_length=128, verbose_name='TestItem')),
                ('PATTERN_NAME', models.CharField(max_length=128, verbose_name='PatternName')),
                ('TEST_CATEGORY', models.CharField(max_length=128, verbose_name='TestGategory')),
                ('TEST_PURPOSE', models.CharField(max_length=128, verbose_name='TestPurpose')),
                ('TEST_PROCESS', models.CharField(max_length=128, verbose_name='TestProcess')),
                ('TEST_NOTES', models.CharField(max_length=128, verbose_name='TestNotes')),
                ('USER', models.CharField(max_length=64, verbose_name='User')),
                ('TIME', models.CharField(max_length=128, verbose_name='Time')),
                ('RTL_VERSION', models.CharField(max_length=128, verbose_name='Rtl_Version')),
                ('NETLIST_VERSION', models.CharField(max_length=128, verbose_name='NetlistVersion')),
                ('SIM_MODE', models.CharField(max_length=128, verbose_name='SimMode')),
                ('TOOL', models.CharField(max_length=64, verbose_name='Tool')),
                ('CORNER', models.CharField(max_length=128, verbose_name='Corner')),
                ('MTM', models.CharField(max_length=128, verbose_name='Mtm')),
                ('SIM_SEED', models.CharField(max_length=128, verbose_name='SimSeed')),
                ('TWO_NODE', models.BooleanField(verbose_name='TwoNode')),
                ('MBIST', models.BooleanField(verbose_name='Mbist')),
                ('FPGA_FLOW', models.CharField(max_length=128, verbose_name='FpgaFlow')),
                ('FPGA_WORK', models.CharField(max_length=128, verbose_name='FpgaWork')),
                ('WORK_PATH', models.CharField(max_length=128, verbose_name='WorkPath')),
                ('LOG_NAME', models.CharField(max_length=128, verbose_name='LogName')),
                ('SIM_RESULTS', models.CharField(max_length=128, verbose_name='SimResults')),
                ('CHECK_WAVE', models.BooleanField(verbose_name='CheckWave')),
                ('JTAG_ACCESS', models.BooleanField(verbose_name='JtagAccess')),
                ('PATTERN_MD5', models.CharField(max_length=128, verbose_name='PatternMd5')),
                ('PROJECT_NAME', models.CharField(max_length=128, verbose_name='ProjectName')),
            ],
        ),
    ]
