# Generated by Django 3.2 on 2023-10-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatternInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninfo',
            name='CHECK_WAVE',
            field=models.BooleanField(null=True, verbose_name='CheckWave'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='CORNER',
            field=models.CharField(max_length=128, null=True, verbose_name='Corner'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='FPGA_FLOW',
            field=models.CharField(max_length=128, null=True, verbose_name='FpgaFlow'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='FPGA_WORK',
            field=models.CharField(max_length=128, null=True, verbose_name='FpgaWork'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='JTAG_ACCESS',
            field=models.BooleanField(null=True, verbose_name='JtagAccess'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='LOG_NAME',
            field=models.CharField(max_length=128, null=True, verbose_name='LogName'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='MBIST',
            field=models.BooleanField(null=True, verbose_name='Mbist'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='MTM',
            field=models.CharField(max_length=128, null=True, verbose_name='Mtm'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='NETLIST_VERSION',
            field=models.CharField(max_length=128, null=True, verbose_name='NetlistVersion'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='PATTERN_MD5',
            field=models.CharField(max_length=128, null=True, verbose_name='PatternMd5'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='PATTERN_NAME',
            field=models.CharField(max_length=128, null=True, verbose_name='PatternName'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='PROJECT_NAME',
            field=models.CharField(max_length=128, null=True, verbose_name='ProjectName'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='RTL_VERSION',
            field=models.CharField(max_length=128, null=True, verbose_name='Rtl_Version'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='SIM_MODE',
            field=models.CharField(max_length=128, null=True, verbose_name='SimMode'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='SIM_RESULTS',
            field=models.CharField(max_length=128, null=True, verbose_name='SimResults'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='SIM_SEED',
            field=models.CharField(max_length=128, null=True, verbose_name='SimSeed'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_CATEGORY',
            field=models.CharField(max_length=128, null=True, verbose_name='TestGategory'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_ITEM',
            field=models.CharField(max_length=128, null=True, verbose_name='TestItem'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_NOTES',
            field=models.CharField(max_length=128, null=True, verbose_name='TestNotes'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_PROCESS',
            field=models.CharField(max_length=128, null=True, verbose_name='TestProcess'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_PURPOSE',
            field=models.CharField(max_length=128, null=True, verbose_name='TestPurpose'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TIME',
            field=models.CharField(max_length=128, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TOOL',
            field=models.CharField(max_length=64, null=True, verbose_name='Tool'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='TWO_NODE',
            field=models.BooleanField(null=True, verbose_name='TwoNode'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='USER',
            field=models.CharField(max_length=64, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='patterninfo',
            name='WORK_PATH',
            field=models.CharField(max_length=128, null=True, verbose_name='WorkPath'),
        ),
    ]
