# Generated by Django 3.2 on 2023-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatternInfo', '0002_auto_20231025_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninfo',
            name='TEST_PROCESS',
            field=models.CharField(max_length=512, null=True, verbose_name='TestProcess'),
        ),
    ]
