# Generated by Django 3.2 on 2023-04-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_uuid', models.CharField(max_length=128, unique=True, verbose_name='IpUuid')),
                ('ip_name', models.CharField(max_length=64, verbose_name='IpName')),
                ('private_project', models.BooleanField(verbose_name='PrivateProject')),
                ('description', models.TextField(verbose_name='IpDescription')),
                ('start_date', models.DateField(verbose_name='StartDate')),
                ('status', models.CharField(max_length=32, verbose_name='Status')),
                ('end_date', models.DateField(verbose_name='EndDate')),
                ('create_user', models.CharField(max_length=64, verbose_name='CreateUser')),
                ('version', models.CharField(default='v1.0', max_length=64, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='RegGatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_gather_uuid', models.CharField(max_length=128, unique=True, verbose_name='RegGatherUuid')),
                ('tag', models.CharField(max_length=64, verbose_name='Tag')),
                ('offset', models.CharField(max_length=64, unique=True, verbose_name='Offset')),
                ('reg_gather_name', models.CharField(max_length=128, verbose_name='RegGatherName')),
                ('description', models.TextField(verbose_name='Description')),
                ('reset', models.CharField(max_length=64, verbose_name='Reset')),
                ('ip_uuid', models.ForeignKey(db_column='ip_uuid', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='IP.ipinfo', to_field='ip_uuid')),
            ],
            options={
                'verbose_name': 'RegGather信息',
                'db_table': 'IP_reggatherinfo',
            },
        ),
        migrations.CreateModel(
            name='SingleRegInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_reg_uuid', models.CharField(max_length=128, unique=True, verbose_name='SingleRegUuid')),
                ('start_bit', models.CharField(max_length=16, verbose_name='StartBit')),
                ('end_bit', models.CharField(max_length=16, verbose_name='EndBit')),
                ('RW', models.CharField(max_length=16, verbose_name='R/W')),
                ('field', models.CharField(max_length=128, verbose_name='Field')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='Note')),
                ('description', models.TextField(verbose_name='Description')),
                ('reg_gather_uuid', models.ForeignKey(db_column='reg_gather_uuid', on_delete=django.db.models.deletion.CASCADE, to='IP.reggatherinfo', to_field='reg_gather_uuid')),
            ],
        ),
        migrations.CreateModel(
            name='ValueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_uuid', models.CharField(max_length=128, unique=True, verbose_name='value_uuid')),
                ('valueId', models.CharField(max_length=64, verbose_name='ValueId')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('description', models.TextField(verbose_name='Description')),
                ('single_reg_uuid', models.ForeignKey(db_column='single_reg_uuid', on_delete=django.db.models.deletion.CASCADE, to='IP.singlereginfo', to_field='single_reg_uuid')),
            ],
        ),
    ]
